exclude: [README.md]
title: Marco Annunziata's blog
email: marco11main@gmail.com
description: Blog, project updates, research
baseurl: ""
url: ""
github: https://github.com/Remdox
authorEmail: marco11main@gmail.com
safe: true
source: .
theme: minima

plugins:
  - jekyll-feed
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

imagesFolder: /assets/images

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      permalink: "/posts/:categories/:title"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
